Algoritmo "para exercicio1a)"
// Disciplina   : [Linguagem e Lógica de Programação com JavaScript]
// Professor   : Jailson Costa
// Descrição   : irá executar um cronometro
// Autor(a)    : milena dias
// Data atual  : 04/04/2024
Var
   // Seção de Declarações das variáveis
   contadora:inteiro
Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   para contadora de 15 ate 200 faca
      escreval(contadora*contadora)
   fimpara
Fimalgoritmo